[build]
  publish = "site/public"
  command = "python convert_notebooks.py  \
             cd site && hugo"

[context.production.environment]
  HUGO_VERSION = "0.55.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
