channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - h5py
  - numba
  - networkx
  - numexpr
  - scipy
  - bokeh
  - rise
  - pip:
    - jupyter-contrib-nbextensions
    - seaborn
